export const ACCOUNT_CONSTANTS = {
  TYPES: ["Posting", "Heading", "Total", "Begin-Total", "End-Total"],
  CATEGORIES: ["Assets", "Liabilities", "Equity", "Revenue", "Expense"],
  POSTING_TYPES: ["Sale", "Purchase", "Inventory", "General", "Fixed Asset"],
  BUSINESS_GROUPS: [
    "Domestic",
    "International",
    "Online",
    "Retail",
    "Wholesale",
  ],
  PRODUCT_GROUPS: [
    "Electronics",
    "Furniture",
    "Services",
    "Software",
    "Hardware",
  ],
  COLUMN_WIDTHS: {
    A: 10,
    B: 15,
    C: 15,
    D: 15,
    E: 15,
    F: 15,
    G: 12,
    H: 10,
    I: 20,
    J: 25,
    K: 25,
    L: 25,
  },
};
