export const ITEM_CONSTANTS = {
  UNITS_OF_MEASURE: ["PCS", "BOX", "CTN", "KG", "M", "L", "SET", "PAIR"],
  DESCRIPTIONS: [
    "Standard Widget",
    "Premium Component",
    "Basic Module",
    "Advanced Assembly",
    "Professional Tool",
    "Industrial Equipment",
    "Commercial Supply",
    "Technical Part",
    "Specialized Device",
    "General Purpose Item",
  ],
  COLUMN_WIDTHS: {
    A: 12,
    B: 30,
    C: 30,
    D: 15,
    E: 12,
    F: 12,
    G: 12,
    H: 12,
    I: 12,
    J: 10,
    K: 12,
    L: 12,
    M: 12,
    N: 12,
    O: 12,
    P: 12,
    Q: 12,
    R: 12,
  },
};
